spring:
    cloud:
        config:
            server:
                git:
                  uri: https://github.com/liuxver/springCloudConfig
                  search-paths:
                  username:
                  password:
            label: master
    application:
        name: config-server
server:
    port: 9991
eureka:
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka/