my:
    name: liuxu
    age: 20
    number: ${random.int}
    uuid: ${random.uuid}
    max: ${random.int(10)}
    value: ${random.value}
    greeting: hi,l am ${my.name}

spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
      username: root
      password: 1234
    jpa:
        hibernate:
          ddl-auto: create  #第一次建表用create 后面用update
        show-sql: true